# 数据源配置
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # 主库数据源
    master:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/wayn_shop?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
      pool-name: hikariCP
      minimum-idle: 100
      maximum-pool-size: 200
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    # 从库数据源
    slave:
      # 从数据源开关/默认关闭
      enabled: false
      url:
      username:
      password:

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 2
      timeout: 300
      lettuce:
        shutdown-timeout: 100ms
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 消息确认配置项
    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      simple:
        # 一个消费者最多可处理的nack（未确认）消息数量
        prefetch: 1
        acknowledge-mode: manual  # 消息确认方式，其有三种配置方式，分别是none、manual(手动ack) 和auto(自动ack) 默认auto

es:
  config:
    host: 127.0.0.1
    port: 9200
    username:
    password:
    scheme: http
    shards: 3
    replicas: 2

# wx支付配置
shop:
  # 开发者应该设置成自己的wx相关信息
  wxpay:
    app-id:
    app-secret:
    mch-id:
    mch-key:
    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: xxxxx
  # alipay
  alipay:
    app-id:
    rsa-private-key:
    alipay-public_key:
    gateway: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    charset: UTF-8
    format: json
    log_path: /opt/waynboot-mall/log
    signtype: RSA2
